spring:
   datasource:
      url: jdbc:mysql://localhost:3306/fighter_information
      username: fighter_information 
      password: fighter_information
   
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true
      defer-datasource-initialization: true
    
      properties: 
         hibernate:
            format_sql: true 
   
   sql:
      init:
         mode: always